### ISSUE TITLE
Memory Footprint too High

### ISSUE THREAD

**Issue by gturenchalk** [macarthur-lab/clinvar#2]
Hello,

I came across your clinvar pipeline via a google search and decided to experiment with it.  It turns out that for the VM I am using, there is a failure because too much memory is required in the parse_clinvar_xml.py stage.

I see that you are parsing the entire ClinVar XML tree at once via an  ET.parse(handle) command.

Have you considered using ET.iterparse() to parse the XML on the fly? I think you could detect the end of ClinVarSet elements, extract info from the element, and then use an elem.clear() to free the memory. An example is discussed at the following link:

http://eli.thegreenplace.net/2012/03/15/processing-xml-in-python-with-elementtree

Thanks for posting your code.

-- Gregory S. Turenchalk

**Comment by ericminikel** [comment]
Thanks @gturenchalk (and thanks to @bw2 who also pointed this out and talked through solutions with me). I have now switched to `iterparse` as of [this commit](https://github.com/macarthur-lab/clinvar/commit/ebd38ba390e938fb587412a2d59a5f7f1a3d4e3b) and it appears to be working.

**Comment by ericminikel** [comment]
Turns out I forgot to add `elem.clear()` on my first go; I have [now](https://github.com/macarthur-lab/clinvar/commit/a3e7e97dbdb4e6782b0d06dd5bb3a22fefe98b4b) added it and successfully ran parse_clinvar_xml.py to completion in under a half hour (used to take 3 hours). I didn't explicitly check peak memory usage but I was able to run it on an interactive node which I couldn't before, so I believe it is much lower.

I will close this issue for now but feel free to re-open if you find that you still have trouble.
